ALTER
ALGORITHM = UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `vi_grid_relvisita` AS
select `relvisita`.`idrelvisita`                                                   AS `idrelvisita`,
       `relvisita`.`codocorrencia`                                                 AS `codocorrencia`,
       `relvisita`.`controle`                                                      AS `controle`,
       `relvisita`.`codcliente`                                                    AS `codcliente`,
       `relvisita`.`dataatendimento`                                               AS `dataatendimento`,
       `relvisita`.`codclisapiens`                                                 AS `codclisapiens`,
       `relvisita`.`nomecliente`                                                   AS `nomecliente`,
       `relvisita`.`consultor`                                                     AS `consultor`,
       ((`HORAPARADEC`(`relvisita`.`normal`) + `HORAPARADEC`(`relvisita`.`fimref`)) -
        `HORAPARADEC`(`relvisita`.`iniref`))                                       AS `nocliente`,
       (`HORAPARADEC`(`relvisita`.`fimref`) - `HORAPARADEC`(`relvisita`.`iniref`)) AS `refeicao`,
       `HORAPARADEC`(`relvisita`.`normal`)                                         AS `trab`,
       `HORAPARADEC`(`relvisita`.`deslocamento`)                                   AS `deslocamento`,
       `HORAPARADEC`(`relvisita`.`hdiretriz`)                                      AS `hdiretriz`,
       `HORAPARADEC`(`relvisita`.`diaria`)                                         AS `diaria`,
       `HORAPARADEC`(`relvisita`.`hextra`)                                         AS `hextra`,
       `HORAPARADEC`(`relvisita`.`meta`)                                           AS `meta`,
       `HORAPARADEC`(`relvisita`.`total`)                                          AS `faturada`,
       `HORAPARADEC`(`relvisita`.`deslocamentooperacional`)                        AS `deslocamentooperacional`,
       `HORAPARADEC`(`relvisita`.`diariaoperacional`)                              AS `diariaoperacional`,
       `relvisita`.`pendencias`                                                    AS `pendencias`,
       `relvisita`.`faturamento`                                                   AS `faturamento`,
       `relvisita`.`motivohdiretriz`                                               AS `motivohdiretriz`,
       `relvisita`.`cidade`                                                        AS `cidade`,
       `relvisita`.`datapreenchido`                                                AS `datapreenchido`,
       `relvisita`.`visto`                                                         AS `visto`,
       `relvisita`.`numeropedido`                                                  AS `numeropedido`,
       `relvisita`.`empresa`                                                       AS `empresa`,
       `relvisita`.`filial`                                                        AS `filial`,
       `relvisita`.`fatura`                                                        AS `fatura`,
       `relvisita`.`status`                                                        AS `status`,
       `relvisita`.`nucleorelatorio`                                               AS `nucleorelatorio`,
       `relvisita`.`historico_deslocamento`                                        AS `historico_deslocamento`,
       `usuarios`.`nome`                                                           AS `nome`,
       `relvisita`.`equipe`                                                        AS `equipe`,
       `arqcf`.`TipEmc`                                                            AS `TipEmc`,
       `relvisita`.`atendido`                                                      AS `atendido`,
       `HORAPARADEC`(`relvisita`.`chegada`)                                        AS `chegada`,
       `HORAPARADEC`(`relvisita`.`saida`)                                          AS `saida`,
       `arqcf`.`NomeCliFor`                                                        AS `NomeCliFor`,
       `usuarios`.`primeironome`                                                   AS `primeironome`,
       `relvisita`.`diaspreenchido`                                                AS `diaspreenchido`,
       `arqcf`.`CodTipoFaturamento`                                                AS `codtipofaturamento`
from ((`relvisita` left join `arqcf` on ((`arqcf`.`CodCliFor` = `relvisita`.`codcliente`)))
         left join `usuarios` on ((`relvisita`.`consultor` = `usuarios`.`idusuario`)));